// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoData.proto

package com.pandj.wewrite;

public final class javaProtoOutput {
  private javaProtoOutput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface protoDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string textAfter = 1;
    /**
     * <code>optional string textAfter = 1;</code>
     */
    boolean hasTextAfter();
    /**
     * <code>optional string textAfter = 1;</code>
     */
    java.lang.String getTextAfter();
    /**
     * <code>optional string textAfter = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextAfterBytes();

    // optional string textBefore = 2;
    /**
     * <code>optional string textBefore = 2;</code>
     */
    boolean hasTextBefore();
    /**
     * <code>optional string textBefore = 2;</code>
     */
    java.lang.String getTextBefore();
    /**
     * <code>optional string textBefore = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBeforeBytes();

    // optional string differText = 3;
    /**
     * <code>optional string differText = 3;</code>
     */
    boolean hasDifferText();
    /**
     * <code>optional string differText = 3;</code>
     */
    java.lang.String getDifferText();
    /**
     * <code>optional string differText = 3;</code>
     */
    com.google.protobuf.ByteString
        getDifferTextBytes();

    // optional int32 cursorLocationAfter = 4;
    /**
     * <code>optional int32 cursorLocationAfter = 4;</code>
     */
    boolean hasCursorLocationAfter();
    /**
     * <code>optional int32 cursorLocationAfter = 4;</code>
     */
    int getCursorLocationAfter();

    // optional int32 cursorLocationBefore = 5;
    /**
     * <code>optional int32 cursorLocationBefore = 5;</code>
     */
    boolean hasCursorLocationBefore();
    /**
     * <code>optional int32 cursorLocationBefore = 5;</code>
     */
    int getCursorLocationBefore();

    // optional int64 globalOrderId = 6;
    /**
     * <code>optional int64 globalOrderId = 6;</code>
     */
    boolean hasGlobalOrderId();
    /**
     * <code>optional int64 globalOrderId = 6;</code>
     */
    long getGlobalOrderId();

    // optional bool valid = 7;
    /**
     * <code>optional bool valid = 7;</code>
     */
    boolean hasValid();
    /**
     * <code>optional bool valid = 7;</code>
     */
    boolean getValid();
  }
  /**
   * Protobuf type {@code WeWrite.protoData}
   */
  public static final class protoData extends
      com.google.protobuf.GeneratedMessage
      implements protoDataOrBuilder {
    // Use protoData.newBuilder() to construct.
    private protoData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private protoData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final protoData defaultInstance;
    public static protoData getDefaultInstance() {
      return defaultInstance;
    }

    public protoData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private protoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              textAfter_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              textBefore_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              differText_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cursorLocationAfter_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cursorLocationBefore_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              globalOrderId_ = input.readInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              valid_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.pandj.wewrite.javaProtoOutput.internal_static_WeWrite_protoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.pandj.wewrite.javaProtoOutput.internal_static_WeWrite_protoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.pandj.wewrite.javaProtoOutput.protoData.class, com.pandj.wewrite.javaProtoOutput.protoData.Builder.class);
    }

    public static com.google.protobuf.Parser<protoData> PARSER =
        new com.google.protobuf.AbstractParser<protoData>() {
      public protoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new protoData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<protoData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string textAfter = 1;
    public static final int TEXTAFTER_FIELD_NUMBER = 1;
    private java.lang.Object textAfter_;
    /**
     * <code>optional string textAfter = 1;</code>
     */
    public boolean hasTextAfter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string textAfter = 1;</code>
     */
    public java.lang.String getTextAfter() {
      java.lang.Object ref = textAfter_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textAfter_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string textAfter = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextAfterBytes() {
      java.lang.Object ref = textAfter_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textAfter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string textBefore = 2;
    public static final int TEXTBEFORE_FIELD_NUMBER = 2;
    private java.lang.Object textBefore_;
    /**
     * <code>optional string textBefore = 2;</code>
     */
    public boolean hasTextBefore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string textBefore = 2;</code>
     */
    public java.lang.String getTextBefore() {
      java.lang.Object ref = textBefore_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textBefore_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string textBefore = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBeforeBytes() {
      java.lang.Object ref = textBefore_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textBefore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string differText = 3;
    public static final int DIFFERTEXT_FIELD_NUMBER = 3;
    private java.lang.Object differText_;
    /**
     * <code>optional string differText = 3;</code>
     */
    public boolean hasDifferText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string differText = 3;</code>
     */
    public java.lang.String getDifferText() {
      java.lang.Object ref = differText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          differText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string differText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDifferTextBytes() {
      java.lang.Object ref = differText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        differText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 cursorLocationAfter = 4;
    public static final int CURSORLOCATIONAFTER_FIELD_NUMBER = 4;
    private int cursorLocationAfter_;
    /**
     * <code>optional int32 cursorLocationAfter = 4;</code>
     */
    public boolean hasCursorLocationAfter() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 cursorLocationAfter = 4;</code>
     */
    public int getCursorLocationAfter() {
      return cursorLocationAfter_;
    }

    // optional int32 cursorLocationBefore = 5;
    public static final int CURSORLOCATIONBEFORE_FIELD_NUMBER = 5;
    private int cursorLocationBefore_;
    /**
     * <code>optional int32 cursorLocationBefore = 5;</code>
     */
    public boolean hasCursorLocationBefore() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 cursorLocationBefore = 5;</code>
     */
    public int getCursorLocationBefore() {
      return cursorLocationBefore_;
    }

    // optional int64 globalOrderId = 6;
    public static final int GLOBALORDERID_FIELD_NUMBER = 6;
    private long globalOrderId_;
    /**
     * <code>optional int64 globalOrderId = 6;</code>
     */
    public boolean hasGlobalOrderId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 globalOrderId = 6;</code>
     */
    public long getGlobalOrderId() {
      return globalOrderId_;
    }

    // optional bool valid = 7;
    public static final int VALID_FIELD_NUMBER = 7;
    private boolean valid_;
    /**
     * <code>optional bool valid = 7;</code>
     */
    public boolean hasValid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool valid = 7;</code>
     */
    public boolean getValid() {
      return valid_;
    }

    private void initFields() {
      textAfter_ = "";
      textBefore_ = "";
      differText_ = "";
      cursorLocationAfter_ = 0;
      cursorLocationBefore_ = 0;
      globalOrderId_ = 0L;
      valid_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextAfterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTextBeforeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDifferTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, cursorLocationAfter_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, cursorLocationBefore_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, globalOrderId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, valid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextAfterBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTextBeforeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDifferTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cursorLocationAfter_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cursorLocationBefore_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, globalOrderId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, valid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.pandj.wewrite.javaProtoOutput.protoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.pandj.wewrite.javaProtoOutput.protoData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeWrite.protoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.pandj.wewrite.javaProtoOutput.protoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.pandj.wewrite.javaProtoOutput.internal_static_WeWrite_protoData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.pandj.wewrite.javaProtoOutput.internal_static_WeWrite_protoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.pandj.wewrite.javaProtoOutput.protoData.class, com.pandj.wewrite.javaProtoOutput.protoData.Builder.class);
      }

      // Construct using com.pandj.wewrite.javaProtoOutput.protoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        textAfter_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        textBefore_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        differText_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cursorLocationAfter_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorLocationBefore_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        globalOrderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        valid_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.pandj.wewrite.javaProtoOutput.internal_static_WeWrite_protoData_descriptor;
      }

      public com.pandj.wewrite.javaProtoOutput.protoData getDefaultInstanceForType() {
        return com.pandj.wewrite.javaProtoOutput.protoData.getDefaultInstance();
      }

      public com.pandj.wewrite.javaProtoOutput.protoData build() {
        com.pandj.wewrite.javaProtoOutput.protoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.pandj.wewrite.javaProtoOutput.protoData buildPartial() {
        com.pandj.wewrite.javaProtoOutput.protoData result = new com.pandj.wewrite.javaProtoOutput.protoData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.textAfter_ = textAfter_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.textBefore_ = textBefore_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.differText_ = differText_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cursorLocationAfter_ = cursorLocationAfter_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cursorLocationBefore_ = cursorLocationBefore_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.globalOrderId_ = globalOrderId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.valid_ = valid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.pandj.wewrite.javaProtoOutput.protoData) {
          return mergeFrom((com.pandj.wewrite.javaProtoOutput.protoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.pandj.wewrite.javaProtoOutput.protoData other) {
        if (other == com.pandj.wewrite.javaProtoOutput.protoData.getDefaultInstance()) return this;
        if (other.hasTextAfter()) {
          bitField0_ |= 0x00000001;
          textAfter_ = other.textAfter_;
          onChanged();
        }
        if (other.hasTextBefore()) {
          bitField0_ |= 0x00000002;
          textBefore_ = other.textBefore_;
          onChanged();
        }
        if (other.hasDifferText()) {
          bitField0_ |= 0x00000004;
          differText_ = other.differText_;
          onChanged();
        }
        if (other.hasCursorLocationAfter()) {
          setCursorLocationAfter(other.getCursorLocationAfter());
        }
        if (other.hasCursorLocationBefore()) {
          setCursorLocationBefore(other.getCursorLocationBefore());
        }
        if (other.hasGlobalOrderId()) {
          setGlobalOrderId(other.getGlobalOrderId());
        }
        if (other.hasValid()) {
          setValid(other.getValid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.pandj.wewrite.javaProtoOutput.protoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.pandj.wewrite.javaProtoOutput.protoData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string textAfter = 1;
      private java.lang.Object textAfter_ = "";
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public boolean hasTextAfter() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public java.lang.String getTextAfter() {
        java.lang.Object ref = textAfter_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          textAfter_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextAfterBytes() {
        java.lang.Object ref = textAfter_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textAfter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public Builder setTextAfter(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        textAfter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public Builder clearTextAfter() {
        bitField0_ = (bitField0_ & ~0x00000001);
        textAfter_ = getDefaultInstance().getTextAfter();
        onChanged();
        return this;
      }
      /**
       * <code>optional string textAfter = 1;</code>
       */
      public Builder setTextAfterBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        textAfter_ = value;
        onChanged();
        return this;
      }

      // optional string textBefore = 2;
      private java.lang.Object textBefore_ = "";
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public boolean hasTextBefore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public java.lang.String getTextBefore() {
        java.lang.Object ref = textBefore_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          textBefore_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBeforeBytes() {
        java.lang.Object ref = textBefore_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textBefore_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public Builder setTextBefore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textBefore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public Builder clearTextBefore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        textBefore_ = getDefaultInstance().getTextBefore();
        onChanged();
        return this;
      }
      /**
       * <code>optional string textBefore = 2;</code>
       */
      public Builder setTextBeforeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textBefore_ = value;
        onChanged();
        return this;
      }

      // optional string differText = 3;
      private java.lang.Object differText_ = "";
      /**
       * <code>optional string differText = 3;</code>
       */
      public boolean hasDifferText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string differText = 3;</code>
       */
      public java.lang.String getDifferText() {
        java.lang.Object ref = differText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          differText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string differText = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDifferTextBytes() {
        java.lang.Object ref = differText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          differText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string differText = 3;</code>
       */
      public Builder setDifferText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        differText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string differText = 3;</code>
       */
      public Builder clearDifferText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        differText_ = getDefaultInstance().getDifferText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string differText = 3;</code>
       */
      public Builder setDifferTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        differText_ = value;
        onChanged();
        return this;
      }

      // optional int32 cursorLocationAfter = 4;
      private int cursorLocationAfter_ ;
      /**
       * <code>optional int32 cursorLocationAfter = 4;</code>
       */
      public boolean hasCursorLocationAfter() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 cursorLocationAfter = 4;</code>
       */
      public int getCursorLocationAfter() {
        return cursorLocationAfter_;
      }
      /**
       * <code>optional int32 cursorLocationAfter = 4;</code>
       */
      public Builder setCursorLocationAfter(int value) {
        bitField0_ |= 0x00000008;
        cursorLocationAfter_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLocationAfter = 4;</code>
       */
      public Builder clearCursorLocationAfter() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorLocationAfter_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cursorLocationBefore = 5;
      private int cursorLocationBefore_ ;
      /**
       * <code>optional int32 cursorLocationBefore = 5;</code>
       */
      public boolean hasCursorLocationBefore() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 cursorLocationBefore = 5;</code>
       */
      public int getCursorLocationBefore() {
        return cursorLocationBefore_;
      }
      /**
       * <code>optional int32 cursorLocationBefore = 5;</code>
       */
      public Builder setCursorLocationBefore(int value) {
        bitField0_ |= 0x00000010;
        cursorLocationBefore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLocationBefore = 5;</code>
       */
      public Builder clearCursorLocationBefore() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cursorLocationBefore_ = 0;
        onChanged();
        return this;
      }

      // optional int64 globalOrderId = 6;
      private long globalOrderId_ ;
      /**
       * <code>optional int64 globalOrderId = 6;</code>
       */
      public boolean hasGlobalOrderId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 globalOrderId = 6;</code>
       */
      public long getGlobalOrderId() {
        return globalOrderId_;
      }
      /**
       * <code>optional int64 globalOrderId = 6;</code>
       */
      public Builder setGlobalOrderId(long value) {
        bitField0_ |= 0x00000020;
        globalOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 globalOrderId = 6;</code>
       */
      public Builder clearGlobalOrderId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        globalOrderId_ = 0L;
        onChanged();
        return this;
      }

      // optional bool valid = 7;
      private boolean valid_ ;
      /**
       * <code>optional bool valid = 7;</code>
       */
      public boolean hasValid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool valid = 7;</code>
       */
      public boolean getValid() {
        return valid_;
      }
      /**
       * <code>optional bool valid = 7;</code>
       */
      public Builder setValid(boolean value) {
        bitField0_ |= 0x00000040;
        valid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool valid = 7;</code>
       */
      public Builder clearValid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        valid_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WeWrite.protoData)
    }

    static {
      defaultInstance = new protoData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WeWrite.protoData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeWrite_protoData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeWrite_protoData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017protoData.proto\022\007WeWrite\"\247\001\n\tprotoData" +
      "\022\021\n\ttextAfter\030\001 \001(\t\022\022\n\ntextBefore\030\002 \001(\t\022" +
      "\022\n\ndifferText\030\003 \001(\t\022\033\n\023cursorLocationAft" +
      "er\030\004 \001(\005\022\034\n\024cursorLocationBefore\030\005 \001(\005\022\025" +
      "\n\rglobalOrderId\030\006 \001(\003\022\r\n\005valid\030\007 \001(\010B$\n\021" +
      "com.pandj.wewriteB\017javaProtoOutput"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WeWrite_protoData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WeWrite_protoData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeWrite_protoData_descriptor,
              new java.lang.String[] { "TextAfter", "TextBefore", "DifferText", "CursorLocationAfter", "CursorLocationBefore", "GlobalOrderId", "Valid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
